apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deploy     #A
spec:
  template:
    spec:
      containers:
      - name: guestbook      #B
        env:                 #C
        - name: DEBUG
          value: "false"

